version: '2'
services:
  netsil:
    image: netsil/netsil:stable-1.4.3
    restart: unless-stopped
    command: ["/root/startup.sh"]
    volumes:
      - /opt/netsil/lite/ceph/conf:/etc/ceph
      - /opt/netsil/lite/ceph/data:/var/lib/ceph-data
      - /opt/netsil/lite/druid/realtime-segments:/opt/netsil/druid/realtime-segments
      - /opt/netsil/lite/druid/indexCache:/var/tmp/druid/indexCache
      - /opt/netsil/lite/elasticsearch/data:/usr/share/elasticsearch/data
      - /opt/netsil/lite/kafka/kafka-log-dir:/opt/netsil/kafka/kafka-log-dir
      - /opt/netsil/lite/license-manager/licenses:/opt/netsil/license-manager/licenses
      - /opt/netsil/lite/mysql/data:/var/lib/mysql
      - /opt/netsil/lite/redis:/var/lib/redis
      - /opt/netsil/lite/zookeeper/data:/opt/netsil/zookeeper/data
    environment:
      - DEPLOY_ENV=docker-compose
    ports:
      - '80:80'
      - '443:443'
      - '2001:2001'
      - '2003:2003'
      - '2003:2003/udp'
    logging:
      driver: none
